path: "/usr/local/bin/incremental-backup"
src: "/"
dst: "/media/austin/LinuxBackups/backups/austins-starbook"
filters:
  type: "merge"
  file: "/usr/local/etc/backup/filters.txt"
# flags: "v"
keep: 14
