#!/usr/bin/env bash

<<comment
Note: it's possible I'll run into a circular dependency issue here: something in
      this file depends on something in the main file, which in turn depends on
      something here. It's mostly an issue of order, so the problem could be
      solved by breaking this up into it's constituent parts. That seems like
      overkill at this point though.
comment

## bootstrap ###################################################################

if ! which brew > /dev/null; then
    echo "[WARN] homebrew is required for this configuration"
fi

export BREW="$(brew --prefix)"

## important paths #############################################################

## bin

export BIN_PARENT="${BREW}"
export BIN="${BREW}/bin"

if [[ ! -d "${BIN}" ]]; then
    echo "[WARN] homebrew binaries not found"
fi

## shell

export SHELL_PATH="${BIN}/bash"

## admin (my) home dir

export ADMIN_HOME="/Users/austin"

## go

export GO_ROOT="${BIN}/go"

## external storage

export VOLUME_ROOT="/Volumes"
export MOUNT_POINT="${VOLUME_ROOT}"

## completions

export COMPLETION_PATH="${BREW}/etc/bash_completion"
export COMPLETION_DIR="${HOME}/.bash_completions"

## path manipulations ##########################################################

## shell path

export PATH="${BIN}:${PATH}"    # homebrew

## aliases #####################################################################

## rename

alias eject="sudo diskutil eject"
alias lsblk="diskutil list"

