# TODO: use these to implement archival
# [limits]
# size = "51200"
# lines = "500000"
# hrs_since_log = ""
# action = "archive"

# TODO: implement enough for archival
# [stats]
# size = { cmd = "du -sh * | awk '{print $1}'" }
# lines = { cmd = "wc -l" }
# hrs_since_log = { cmd = "" }
# pfx = { cmd = "" }
# level = { cmd = "" }

# TODO: implement archival
# [actions]
# archive = { run = "" }
# clean = { run = "" }
# purge = { run = "" }
