#!/usr/bin/env bash


## init logging ################################################################

export LOG_ROOT="${HOME}/.local/state/logs"
export CURRENT_LOG_LEVEL="WARN"
export DEFAULT_LOG_LEVEL="WARN"
export DEFAULT_LOG_TYPE="default"

## source primary config #######################################################

source "${HOME}/.bashrc"

