# vim: set filetype=tmux :

## open/close ##################################################################

# open
bind-key -n M-n new-window
# close
bind-key -n M-z kill-window

## position ####################################################################

# shift left/right
bind-key -n M-S run-shell "tmux-shift-window -d l"
bind-key -n M-s run-shell "tmux-shift-window -d r"

## navigation ##################################################################

# use 'p' instead of 'l' to switch to previous window
bind-key p previous-window

# extra window switching bindings for keyboard + closer to nvim
bind-key -n M-\{ previous-window
bind-key -n M-\} next-window

# for convenience on laptop keyboards
bind-key -n M-l previous-window
bind-key -n M-\; next-window

# extra window switching bindings for keyboard + closer to nvim
bind-key -n M-! select-window -t 1
bind-key -n M-@ select-window -t 2
bind-key -n M-# select-window -t 3
bind-key -n M-$ select-window -t 4
bind-key -n M-% select-window -t 5
bind-key -n M-^ select-window -t 6
bind-key -n M-& select-window -t 7
bind-key -n M-* select-window -t 8
bind-key -n M-( select-window -t 9
