#!/bin/bash


<<comment
Note: it's possible I'll run into a circular dependency issue here: something in
      this file depends on something in the main file, which in turn depends on
      something here. It's mostly an issue of order, so the problem could be 
      solved by breaking this up into it's constituent parts. That seems like 
      overkill at this point though.
comment


## constants ###################################################################

## identifiers

export readonly MACHINE="StarBook"
export readonly MACHINE_NICKNAME="⭐📖"

## important paths ###########################################################

## external storage

export readonly VOLUME_ROOT="/media"
export readonly MOUNT_POINT="${VOLUME_ROOT}/${USER}"

## home dir

export readonly VIDEOS="${HOME}/Videos"

## aliases #####################################################################

## rename

alias dbc="dbxcli"
alias dp2="devilspie2"

## utils

# copy/paste
alias pbcopy='xsel --clipboard'
alias pbpaste='xsel --clipboard'

# customization
alias gogh='bash -c "$(wget -qO- https://git.io/vQgMr)"'

# system
alias reboot="sudo systemctl reboot -i"

## github ######################################################################

alias pr-create="gh pr create -a \"@me\""

## functions ###################################################################

## navigation

switch() {
    repo="$(ls ${PROJECTS_ROOT} | fzf +i +m -e --height=1%)"
    cd ${PROJECTS_ROOT}/${repo}
}

## utils

open() {
    xdg-open "${1}" > /dev/null 2>&1
}

