#!/usr/bin/env bash


<<comment
Note: it's possible I'll run into a circular dependency issue here: something in
      this file depends on something in the main file, which in turn depends on
      something here. It's mostly an issue of order, so the problem could be
      solved by breaking this up into it's constituent parts. That seems like
      overkill at this point though.
comment


## constants ###################################################################

## identifiers

export MACHINE="MacBook"
export MACHINE_NICKNAME="🍎📖"

## important paths #############################################################

## granica

export WORK_ROOT="${CODE_ROOT}/granica"

## aliases #####################################################################

### rename

alias gl="glab"
alias kc="kubectl"
alias tf="terraform"
alias tg="terragrunt"

### glab

alias gl-pr-create=""

## tools #######################################################################

## glab

if [[ -z "${GITLAB_TOKEN+x}" ]]; then
    GITLAB_TOKEN="$(op-get "GitLab - Granica (API)" "credential")"
fi

