#!/usr/bin/env bash


## init logging ################################################################

export LOG_ROOT="${STD_LOG}"
export CURRENT_LOG_LEVEL="WARN"
export DEFAULT_LOG_LEVEL="WARN"
export DEFAULT_LOG_TYPE="default"

## source primary config #######################################################

source "${HOME}/.bashrc"

