## repos #######################################################################

[repos]
superman = "${HOME}/Workspace/workspace/granica/superman"
krypton = "${HOME}/Workspace/workspace/granica/krypton"

## aliases #####################################################################

[alias.command]
au = "autoupdate"
c = "config"
tf = "terraform"
v = "version"

[alias.directive]
nothing = "do-nothing"
n = "do-nothing"
dn = "do-nothing"
install = "install-rpm"
rpm = "install-rpm"
ir = "install-rpm"
software = "software-apply"
sa = "software-apply"
infra = "infra-apply"
ia = "infra-apply"

[alias.admin]
dash = "dashboard"
dpl = "deploy"
in = "install"
re = "reinstall"

## autoupdate workflows ########################################################

[directive.workflow.deploy]
"do-nothing" = "install-rpm"
"install-rpm" = "infra-apply"
"infra-apply" = "software-apply"
"software-apply" = "do-nothing"

[directive.workflow.command]
"do-nothing" = "custom"
"custom" = "do-nothing"

## customers ###################################################################

[customer]
default = "qtmscreen"

[customer.qtmscreen]
cloud = "gcp"
region = "us-central1"
deployment = "qtms-us-central1"
version_format = "v${VERSION}-qtmscreen"
log_bucket = "n-logs-qtms-us-central1/qm-granica-screen-gke-26c2-29cc"

[customer.qtmscreen.monitoring]
tellus = "https://tellus.gke.qtms-us-central1.bolt.projectn.co"
internal = "http://34.36.182.44"

## environments ################################################################

[env]
default = "validation"

[env.uat]
cloud = "gcp"
admin_server = "project-n-admin-server-255d26"
project = "n-hawkeye-dev"
zone = "us-central1-c"

[env.validation]
cloud = "gcp"
admin_server = "project-n-admin-server-f206a9"
project = "project-n-88f034c9"
zone = "us-central1-c"

## terraform ###################################################################

[alias.terraform]
a = "apply"
p = "plan"
s = "show"

[terraform]
default = "screen"

[terraform.profiles]
screen = "screen/tf/aws"
"aws-tellus" = "tellus-multitenant/eks"
"gpc-tellus" = "tellus-multitenant/gke"
