#!/usr/bin/env bash


<<comment
Note: it's possible I'll run into a circular dependency issue here: something in
      this file depends on something in the main file, which in turn depends on
      something here. It's mostly an issue of order, so the problem could be 
      solved by breaking this up into it's constituent parts. That seems like 
      overkill at this point though.
comment


## constants ###################################################################

## identifiers

export readonly MACHINE="Darter"
export readonly MACHINE_NICKNAME="🏎️"

## important paths ###########################################################

## external storage

export readonly VOLUME_ROOT="/media"
export readonly MOUNT_POINT="${VOLUME_ROOT}/${USER}"

## home dir

export readonly VIDEOS_DIR="Videos"

## aliases #####################################################################

## rename

alias bat="batcat"
alias dbc="dbxcli"
alias dp2="devilspie2"
alias fp="flatpak"

## utils

# copy/paste
alias pbcopy='xsel --clipboard'
alias pbpaste='xsel --clipboard'

# customization
alias gogh='bash -c "$(wget -qO- https://git.io/vQgMr)"'

# system
alias reboot="sudo systemctl reboot -i"

## tools

# tmp: disables the laptop keyboard so I can put a keyboard on top of it while 
#      my laptop keyboard is broken
alias float-keyboard="xinput float $(xinput list --id-only 'AT Translated Set 2 keyboard')"
alias xls="xinput list"

## github ######################################################################

alias pr-create="gh pr create -a \"@me\""

## functions ###################################################################

## utils

open() {
    xdg-open "${1}" > /dev/null 2>&1
    guake -t
}

