#!/usr/bin/env bash

set -Eeuo pipefail


USAGE="shift-window -d l[eft]|r[ight] [-n num]"

usage() {
    echo "usage: ${USAGE}"
}

help() {
cat <<help
DESCRIPTION

    Shifts tmux windows -n windows in the direction provided by -d.

USAGE

    ${USAGE}

OPTIONS

    -d, --direction     l[eft] or r[ight]; the direction in which to shift the window
    -n, --num           optional, defaults to 1; integer; the number of places to shift the window
    -h, --help          display this message
help
}


DIRECTION=""
NUM="1"

while [[ $# -gt 0 ]]; do
  case $1 in
    -d|--direction)
      DIRECTION="$([[ -z "${2+x}" ]] && echo "" || echo "${2}")"
      shift
      shift
      ;;
    -n|--num)
      NUM="${2}"
      shift
      shift
      ;;
    -h|--help)
      help
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done


if [[ -z "${DIRECTION}" ]]; then
    echo "-d|--direction is a required parameter"
    exit 1
fi

if [[ "${DIRECTION}" != +(l|left|r|right) ]]; then
    echo "-d|--direction must be one of l[eft]|r[ight]"
    exit 1
fi

SIGN="$([[ "${DIRECTION}" =~ l(eft)? ]] && echo "-" || echo "+")"
TO_SHIFT_IDX="$(tmux display-message -p "#I")"
NEW_IDX="$((${TO_SHIFT_IDX} "${SIGN}" "${NUM}"))"

tmux swap-window -d -s "${TO_SHIFT_IDX}" -t "${NEW_IDX}"

