path: "/usr/local/bin/take-snapshot"
src: "/"
dst: "/media/austin/LinuxBackups/snapshots/austins-starbook"
filters:
  type: "merge"
  file: "/usr/local/etc/snapshot/filters.txt"
# flags: "v"
keep: 14
