#!/bin/bash

## constants ###################################################################

## identifiers

export readonly MACHINE="MacBook"
export readonly MACHINE_NICKNAME="🍎📖"

## important paths #############################################################

## development

export readonly SIGMA_ROOT="${HOME}/sigma"

## external storage

export readonly VOLUME_ROOT="/Volumes"
export readonly MOUNT_POINT="${VOLUME_ROOT}"

## home dir
 
export readonly VIDEOS="${HOME}/Movies"

## path manipulations ##########################################################

## shell

export PATH="$PATH:$HOME/.jenv/bin:${HOME}/go/bin"
export PATH="${HOME}/Library/Python/3.7/lib/python/site-packages:$PATH"
export PATH="${HOME}/Documents/scripts/bin/git:$PATH"
export PATH="${HOME}/.sigma/scripts:$PATH"
export PATH="${HOME}/.local/bin:$PATH"
export PATH="${HOME}/go/bin:$PATH"

## aliases ###################################################################

## rename

alias eject="sudo diskutil eject"
alias lsblk="diskutil list"
alias pip="pip3"
alias python="python3"
alias tf="terraform"
alias tg="terragrunt"

## sigma 

alias build-ka="cd ~/sigma/mono-go/kubeapply && make install && cd -" 
alias k8s-sec-yaml=="kc get secret $1 -o yaml > ~/Downloads/secrets/yaml/$1.yaml"
alias kcpa="kc get po -l app="
alias sga="sig-auth"
alias sig="cd ~/sigma"
alias oc-jrnl="nvim /Users/austinsherron/sigma/infra-oncall/journal/03062023-03132023.md"
alias oracle="curl \"https://resolv.sigmacomputing.com/api/v1/organizations/$1/$2\""
 
## sigma service config ########################################################

# should come before tooling setup, as some variables (i.e.: CLOUDSDK_PYTHON) get overwritten when we source this
source "$HOME/.sigmarc"

## git #########################################################################

## cli autocompletion

source ~/.git-completion.bash

## github ######################################################################

alias pr-create="gh pr create -a \"@me\" -r \"sigmacomputing/infra\""

# atlantis commands via pr comments
alias tf-pr-apply="gh pr comment -b 'atlantis apply'"
alias tf-pr-diff="gh pr comment -b 'atlantis plan'"

# kubeapply commands via pr comments
alias k8s-pr-apply="gh pr comment -b 'kubeapply apply'"
alias k8s-pr-diff="gh pr comment -b 'kubeapply diff'"

## python ######################################################################

eval "$(pyenv init -)"

## gcloud ######################################################################

## configure

# add to path 
source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc"

# add autocompletions
source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"

# to ensure python3 executable is picked up w/ python virtualenv
export CLOUDSDK_PYTHON="/Users/austinsherron/.pyenv/shims/python3"

## kube* #######################################################################

## constants

export KUBEAPPLY_DIFF_IGNORES="/Users/austinsherron/sigma/mono-go/kubeapply/conf/diff_ignores"
export KUBE_EDITOR="nvim"
export KUBECONFIG="/Users/austinsherron/.kube/config"

## aliases

# kubectl
alias kubectl="kubecolor"
alias kc="kubecolor"

# kubeapply
alias kae="kubeapply expand --clean"
alias kad="kubeapply diff"
alias kaa="kubeapply apply"
alias ska="sig-kubeapply"

## autocompletion

# for kubetcl
source <(kubectl completion bash)
complete -F __start_kubectl kc

## functions  ##################################################################

## auth

gcloud-auth() {
    gcloud auth login
}

aws-auth() { 
    gimme-aws-creds --profile ${1}
    export AWS_PROFILE="${1}"
}

## sig-kubeapply

ka-clean() {
    rm -rf ~/sigma/k8s-configs/expanded/$1
    git checkout -- ~/sigma//k8s-configs/expanded/$1
}

ka-diff() {
    subpath=""

    if [ "$#" -eq 2 ]; then
        subpath="--subpath ${2}"
    fi

    echo $subpath

    eval "kubeapply expand ~/sigma/k8s-configs/kubeapply-conf/local/$1.yaml" 
    eval "kubeapply diff ~/sigma/k8s-configs/kubeapply-conf/local/$1.yaml ${subpath}"

    ka-clean $1
}

ka-apply() {
    subpath=""

    if [ "$#" -eq 2 ]; then
        subpath="--subpath ${2}"
    fi

    echo $subpath

    eval "kubeapply expand ~/sigma/k8s-configs/kubeapply-conf/local/$1.yaml" 
    eval "kubeapply apply ~/sigma/k8s-configs/kubeapply-conf/local/$1.yaml ${subpath}"

    ka-clean $1
}

## tf/tg

tg-clean() {
    find /Users/austinsherron/sigma/sigma-terraform/$1/$2/ -name ".terra*" -exec rm -rf {} +
    rm -rf /Users/austinsherron/sigma/sigma-terraform/$1/$2/out
}

## k8s

get-tls-cert() {
    extract=""

    if [[ "${2}" = "-e" ]]; then
        extract=" | grep -i \"not after\""
    elif [[ "${2}" = "-d" ]]; then
        extract=" | grep -i \"dns\""
    fi

    kc get secret "${1}" -o jsonpath='{.data.tls\.crt}' | base64 -d | openssl x509 -noout -text"${extract}"
}

