filter_mode = "host"
inline_height = 30
keymap_mode = "vim-insert"
# TODO: need to test this on linux, possible I wouldn't want it (or can't have it?) there
ctrl_n_shortcuts = "true"

[keymap_cursor]
vim_insert = "blink-bar"
vim_normal = "steady-block"
