#!/usr/bin/env bash


## bootstrap ###################################################################

if ! which brew > /dev/null; then
    echo "[WARN] homebrew is required for this configuration"
fi

BREW="$(brew --prefix)"
export BREW

## important paths #############################################################

# NOTE: SYS_BIN is set in shared_paths.sh
if [[ ! -d "${SYS_BIN}" ]]; then
    echo "[WARN] homebrew binaries not found"
fi

## go

export GO_ROOT="${SYS_BIN}/go"

## external storage

export VOLUME_ROOT="/Volumes"
export MOUNT_POINT="${VOLUME_ROOT}"

## completions

export COMPLETION_PATH="${BREW}/etc/bash_completion"
export COMPLETION_DIR="${HOME}/.bash_completions"

## aliases #####################################################################

## rename

alias eject="sudo diskutil eject"
alias lsblk="diskutil list"

