# vim: set filetype=tmux :

# change shortcut key binding
unbind C-b
set -g prefix `
bind ` send-prefix

# start counting windows/panes at 1, instead of 0
set -g base-index 1
setw -g pane-base-index 1

# set escape-time to 0
set -sg escape-time 0

# rebind detach to prefix + D (instead of prefix + d)
unbind d
bind-key D detach-client

# ensure windows reindex when one is closed
set-option -g renumber-windows on

# keep the index overlay up until a pane is chosen or <esc> is pressed
set-option -g display-panes-time 3600000
