#!/usr/bin/env bash


if [[ -z "${COMPLETION_DIR+x}" ]]; then
    echo "[ERROR] completions dir env var is unset"
    return 1
fi

if [[ ! -d "${COMPLETION_DIR}" ]]; then
    echo "[INFO] creating completions dir='${COMPLETION_DIR}'"
    mkdir "${COMPLETION_DIR}"
fi

for file in $(ls "${COMPLETION_DIR}"); do
    source "${COMPLETION_DIR}/${file}"
done

