#!/usr/bin/env bash


## bootstrap ###################################################################

export CONFIG_ROOT_PUB="${HOME}/.config"
export SHELL_NAME="$(basename "${SHELL}")"
export SHELL_ROOT="${CONFIG_ROOT_PUB}/shell/${SHELL_NAME}"
export HELPERS_ROOT="${CONFIG_ROOT_PUB}/shell/${SHELL_NAME}/helpers"
export HOST_CONFIG_ROOT="${SHELL_ROOT}/host"

# so functions can be used in rc, osrc, and hostrc
source "${HELPERS_ROOT}/functions.sh"

## os specific config ##########################################################

OS="$(uname | tr [:upper:] [:lower:])"
OS_SPC_ROOT="${HOST_CONFIG_ROOT}/${OS}"
OS_SPC_RC="${OS_SPC_ROOT}/osrc"

# this machine os's config
if [[ -f "${OS_SPC_RC}" ]]; then
    source "${OS_SPC_RC}"
else
    echo "[WARN] no os specific config found for os='${OS}' (path=${OS_SPC_RC})"
fi

## imports #####################################################################

source /etc/profile.d/shared_paths.sh
source "${CODE_ROOT}/lib/bash/utils.sh"

## constants ###################################################################

### identifiers

## me

export ME="austinsherron"
export MY_NICKNAME="austin"
export ME_FORMALLY="Austin Sherron"
export MY_EMAIL="austin@pryvate.email"
export MY_KEY_ID="D55F49224387A57E0FDB80E1494E1B61A3505B41"

## editors

export EDITOR="nvim"
export LEGACY_EDITOR="vim"

## git

export TRUNK="master"

## important paths #############################################################

### interface points

export LEGACY_CONFIG_ROOT_PUB="${HOME}"
export NVIM_ROOT_PUB="${CONFIG_ROOT_PUB}/nvim"
export TMUX_ROOT_PUB="${CONFIG_ROOT_PUB}/tmux"
export TMUX_CONF_PUB="${CONFIG_ROOT_PUB}/tmux/tmux.conf"
export INSTALL_SCRIPTS="${CODE_ROOT}/scripts/install"
export LOG_ROOT="${HOME}/.local/state/logs"

### development

export EDITORS_ROOT="${CONFIG_ROOT}/editors"

### shell

export RC_NAME="${SHELL_NAME}rc"
export RC="${LEGACY_CONFIG_ROOT_PUB}/.${RC_NAME}"
export EXTENSIONS_ROOT="${SHELL_ROOT}/extensions"

### tooling

## vim

export VIM_PARENT="${EDITORS_ROOT}"
export VIM_ROOT="${VIM_PARENT}/vim"
export VIMRC="${VIM_ROOT}/.vimrc"
export VUNDLE="${VIM_ROOT}/.vim"

## nvim

export NVIM_INSTALL="${BIN_PARENT}/nvim/bin"
export NVIM_PARENT="${DEV_ROOT}"
export NVIM_ROOT="${NVIM_PARENT}/nvim"
export NVIMRC="${NVIM_ROOT}/init.lua"
export NVUNDLE="${NVIM_ROOT}/packages"
export NVIM_SUBMODULE="${EDITORS_ROOT}/nvim"

## tmux

export TMUX_ROOT="${TOOLING_ROOT}/tmux"
export TMUX_CONF="${TMUX_ROOT}/tmux.conf"
export TMUX_BUNDLE="${TMUX_ROOT}/plugins"

### remote storage

export REMOTE_ROOT="${HOME}/Remote"
export DROPBOX_ROOT="${REMOTE_ROOT}/Dropbox"

## host specific config ########################################################

HOST="$(hostname -s)"
HOST_SPC_ROOT="${HOST_CONFIG_ROOT}/${HOST}"
HOST_SPC_RC="${HOST_SPC_ROOT}/hostrc"

if [[ -f "${HOST_SPC_RC}" ]]; then
    source "${HOST_SPC_RC}"
else
    echo "[WARN] no host specific config found for host='${HOST}' (path=${HOST_SPC_RC})"
fi

# source optional appearance customization file, if it exists
[[ -f "${HOST_SPC_ROOT}/appearance.sh" ]] && source "${HOST_SPC_ROOT}/appearance.sh"

## path manipulations ##########################################################

### go path

export GOPATH="${HOME}/.go"

### shell path

export PATH="${PATH}:${NVIM_INSTALL}"                   # neovim
export PATH="${PATH}:${GO_ROOT}/bin:${GOPATH}/bin"      # golang
export PATH="${PATH}:/usr/local/jdk-20.0.1/bin"         # java

### pythonpath

## FIXME: I hate having to manually add things here
export PYTHONPATH="${PYTHONPATH}:${CODE_ROOT}/lib/python"
export PYTHONPATH="${PYTHONPATH}:${CODE_ROOT}/interview-prep/utils"
export PYTHONPATH="${PYTHONPATH}:${CODE_ROOT}/finance/src"
export PYTHONPATH="${PYTHONPATH}:${CODE_ROOT}/py-toolbox/tools"

### lua path

# note: as with PYTHONPATH, I'd rather not have to specify the lua path like this,
#       as it makes the scripts that rely on the path significantly less portable; at the
#       time of writing, however (03/14/2023 [pi day!]), I don't know a better solution to
#       the problem of importing homegrown modules

LUA_PATH="$(lua-path -d "${NVIM_ROOT}" -d "${CODE_ROOT}" -d "${CONFIG_ROOT}")"
LUA_PATH="${LUA_PATH};/usr/local/share/lua/5.3/?.lua"      # for luarocks
LUA_PATH="${LUA_PATH};/usr/local/share/lua/5.3/?/init.lua" # for luarocks
LUA_PATH="${LUA_PATH};/usr/local/lib/lua/5.3/?.lua"
LUA_PATH="${LUA_PATH};/usr/local/lib/lua/5.3/?/init.lua"

export LUA_PATH

## shell #######################################################################

### behavior

# append to + reload history = history shared b/w tmux panes, amongst other things
export PROMPT_COMMAND="history -a; history -n"

## helpers #####################################################################

source "${HELPERS_ROOT}/aliases.sh"
source "${HELPERS_ROOT}/extensions.sh"
source "${HELPERS_ROOT}/tools.sh"

