#!/usr/bin/env bash


warning() {
cat <<warning
================================================================================
!                              !!!! WARNING !!!!                               !
!                                                                              !
!                                                                              !
! It appears this is a new system. Good going there good buddy. But not only   !
! is it new and foreign, you don't even have a "backup config" dir for this    !
| os.                                                                          !
!                                                                              !
!                           Get your shit together!                            !
================================================================================
warning
}

warning

## constants ###################################################################

## identifiers

export readonly MACHINE="Unknown Machine"
export readonly MACHINE_NICKNAME="❓🤖"

