#!/usr/bin/env bash


cat <<comment
Note: it's possible I'll run into a circular dependency issue here: something in
      this file depends on something in the main file, which in turn depends on
      something here. It's mostly an issue of order, so the problem could be
      solved by breaking this up into it's constituent parts. That seems like
      overkill at this point though.
comment


## constants ###################################################################

## identifiers

export MACHINE="Darter"
export MACHINE_NICKNAME="🏎️"

## aliases #####################################################################

## move mouse (assumes monitor configurations similar to home office on 06/17/2023)
##
## TODO: mouse movement to specific monitors doesn't work when resolution changes; figure
##       out how to deal w/ this programmatically  (xdotool getwindowgeometry isn't being
##       cooperative)

# to spc monitors

# to ~ center of left; click
# alias lmv="xdotool mousemove 3001 2289 click 1"
alias lmv="xdotool mousemove 1576 1035 click 1"         # two large monitors, l hz, r vr
# alias lmv="xdotool mousemove 895 1458 click 1"        # laptop + one large monitors, r hz
# to ~ center of right; click
# alias rmv="xdotool mousemove 7509 1938 click 1"
alias rmv="xdotool mousemove 3937 1009 click 1"         # two large monitors, l hz, r vr
# alias rmv="xdotool mousemove 2628 1023 click 1"       # laptop + one large monitors, r hz

