#!/usr/bin/env bash


## important paths ###########################################################

## interface points

export APP_IMAGES="${HOME}/Applications"

## completions

export COMPLETION_PATH="/usr/share/bash-completion/bash_completion"
# TODO: verify this path
export COMPLETION_DIR="${HOME}/.local/share/bash-completion/completions"

## go path

export GOPATH="${HOME}/.go"

## aliases #####################################################################

### rename

alias bat="batcat"
alias dbc="dbxcli"
alias dp2="devilspie2"
alias fp="flatpak"
alias pm="pkgmgr"

### utils

## copy/paste

alias pbcopy='xsel --clipboard'
alias pbpaste='xsel --clipboard'

## system

alias reboot="sudo systemctl reboot -i"
alias sc="systemctl"
alias uc="systemctl --user"

## functions ###################################################################

## utils

open() {
    xdg-open "${1}" > /dev/null 2>&1
    guake -t
}

## tools #######################################################################

export GCM_CREDENTIAL_STORE="gpg"

